__CF.vglnk_hash={key:"9b4efad421c8b103b2c94b796db973b0",api_url:("https:"==document.location.protocol?"https://":"http://")+"api.viglink.com/api",cuid:"CF_NOT_DEFINED",dev:false};__CF.precache_cookie_name="CF_PRECACHED";__CF.viglink_default_cfid="CF_DEFAULT_CFID";__CF.viglink_default_zid="-1";__CF.setCookie=function(i,f,k){var m=new Date;m.setDate(m.getDate()+k);document.cookie=i+"="+escape(f)+(k==null?"":";expires="+m.toUTCString())};
__CF.isCookieSet=function(i){if(document.cookie.length>0)if(document.cookie.indexOf(i+"=")!=-1)return true;return false};
__CF.loadCFFeatures=function(){if(!__CF.u||!__CF.p||__CF.p=="-"){if(__CF.o==1){__CF.vglnk_hash.cuid=__CF.viglink_default_cfid;__CF.vglnk_hash.zid=__CF.viglink_default_zid;__CF.vglnk_load()}}else return __CF.sendRequest(__CF.u+__CF.p+".json",function(i){i=eval("("+i.responseText+")");if(i.top_static&&i.top_static.length){__CF.tops=i.top_static;__CF.c==1&&!__CF.isCookieSet(__CF.precache_cookie_name)&&setTimeout("__CF.precache()",1E3)}if(i.cuid&&__CF.o==1){__CF.vglnk_hash.cuid=i.cuid;__CF.vglnk_hash.zid=
i.zid;__CF.vglnk_load()}},function(){__CF.vglnk_hash.cuid=__CF.viglink_default_cfid;__CF.vglnk_hash.zid=__CF.viglink_default_zid;__CF.vglnk_load()})};
__CF.vglnk=function(i){var f={},k,m,d={bind:function(a,b){return function(){return a.apply(b,arguments)}},browser:function(){var a,b={},c,e=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);for(a=0;a<e.length;a++){c=(/[\/ :]([^\/ :]+)$/.exec(e[a])||[])[1];b[c?e[a].substr(0,e[a].length-c.length-1):e[a]]=c||true}return{ie:b.msie,ios:b.mobile&&b.safari,opera:b.opera,playstation:b.playstation}}(),cache:function(){var a={},
b="vglnk_"+(new Date).getTime(),c=0;return function(e,g,h){var j=e[b];if(!j&&h===undefined)return null;j||(j=++c);if(!a[j]){e[b]=j;a[j]={}}if(h!==undefined)a[j][g]=h;return typeof g==="string"?a[j][g]:a[j]}}(),canonicalizeHostname:function(a){if(typeof a==="string")a=d.createA(a);return a.hostname?a.hostname.toString().replace(/^www\./,"").toLowerCase():""},clone:function(a){return d.extend({},a)},createA:function(a,b){return d.createEl("a",{href:a,target:b})},createEl:function(a,b,c){var e;a=document.createElement(a);
b=b||{};c=c||{};for(e in b)a[e]=b[e];for(e in c)a.style[e]=c[e];return a},destructing:function(a){return function(b){var c=false,e;return function(){if(!c){e=b.apply(null,arguments);c=true}return e}}(a)},escapeRegExp:function(){var a;return function(b){a=a||RegExp("([.*+?^${}()|[\\]\\\\])","g");return b.replace(a,"\\$1")}}(),eventLink:function(a){a=a.target||a.srcElement;var b;do if(a.nodeType===1){b=a.tagName.toUpperCase();if(b==="A"||b==="AREA")return a}while(a=a.parentNode)},exceptionLogger:function(){var a=
function(){};return function(b,c){if(c)a=b;else return function(){if(f.dev)return b.apply(this,arguments);else try{return b.apply(this,arguments)}catch(e){a(e)}}}}(),extend:function(){var a,b,c,e,g=arguments.length,h=arguments[0]||{};for(b=1;b<g;b++){e=arguments[b];if(e!==undefined&&e!==null)for(c in e){a=e[c];if(h!==a)if(a!==undefined)h[c]=a}}return h},isArray:function(a){return d.type(a)==="array"},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||a.returnValue===
false||a.defaultPrevented===true},jsonp:function(a,b,c){var e,g;c=d.extend({fn:function(){},"return":false,timeout:null},c);if(typeof c.fn==="string")b=d.extend(b,{jsonp:c.fn});else if(typeof c.fn==="function"){e=d.destructing(c.fn);g=d.uniqid("vglnk_jsonp_");b=d.extend(b,{jsonp:g});window[g]=d.exceptionLogger(function(){e.apply(this,arguments);window[g]=undefined});c.timeout!==null&&setTimeout(d.exceptionLogger(e),c.timeout)}b=d.toQuery(b);a=d.createEl("script",{type:"text/javascript",src:a+(b.length?
"?":"")+b});if(c["return"])return a.src;else{c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)}},on:function(){var a;return function(b,c,e){var g,h;if(arguments.length===1)a=b;else{if(arguments.length===2){if(!a)return;e=c;c=b;b=a}try{g=b["on"+c]}catch(j){}if(typeof g==="function")b["on"+c]=function(n){n=n||window.event;var l=g.apply(b,arguments);n.returnValue=l!==undefined?l:n.returnValue;return n.returnValue};h=function(){if(a.enabled())return e.apply(null,arguments)};
if(b.addEventListener)b.addEventListener(c,h,false);else b.attachEvent&&b.attachEvent("on"+c,h)}}}(),preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=false},ready:function(){var a=false,b=[],c=false,e,g,h,j,n;if(document.addEventListener)h=function(){document.removeEventListener("DOMContentLoaded",h,false);n()};else if(document.attachEvent)j=function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",j);n()}};e=function(){if(!a){a=
true;if(document.readyState==="complete")return n();else if(document.addEventListener)document.addEventListener("DOMContentLoaded",h,false);else if(document.attachEvent){document.attachEvent("onreadystatechange",j);var l=false;try{l=window.frameElement===null}catch(p){}document.documentElement.doScroll&&l&&g()}d.on(window,"load",n)}};g=function(){if(!c){try{document.documentElement.doScroll("left")}catch(l){setTimeout(g,1);return}n()}};n=function(){if(!c){if(!document.body)return setTimeout(d.exceptionLogger(n),
13);c=true;if(b){var l,p=b.length;for(l=0;l<p;l++)b[l]();b=null}}};return function(l){e();c?l():b.push(l)}}(),reformatKeys:function(a){var b,c,e=function(g){return"_"+g.toLowerCase()};for(b in a){c=b.replace(/([A-Z])/,e);if(d.type(a[b])==="object")a[b]=d.reformatKeys(a[b]);if(c!==b){a[c]=a[b];delete a[b]}}return a},toQuery:function(a){var b,c="";for(b in a)if(a[b]!==null&&a[b]!==undefined)c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a[b]);return c.substr(1)},type:function(a){return a===null?
"null":a===undefined?"undefined":Object.prototype.toString.call(a).slice(8,-1).toLowerCase()},uniqid:function(){var a=0;return function(b){return(b?b:"")+(new Date).getTime()+a++}}()},o={api:function(a,b,c){return d.jsonp(f.api_url+"/"+a,d.extend({cuid:f.cuid,format:"jsonp",key:f.key,drKey:f.key?null:f.dr_key,loc:location.href,subId:f.sub_id,v:1},b),c)},addEventListener:function(a,b){this.fire(a,b)},click:function(){var a,b;a=function(c,e){if(e!=="_self"&&(d.browser.ie||d.browser.opera))return"go";
try{if(c.document===undefined)throw true;return"jsonp"}catch(g){return"go"}};b=function(c){c=window.open("",c);c.focus();return c};return function(c,e){e=c.target||e||"_self";e=e===window.name?"_self":e;var g,h,j=b(e),n=a(j,e);g=d.destructing(d.bind(function(){f.time_click&&arguments.length&&this.logTime("clk");var l=Array.prototype.slice.call(arguments);l.unshift(c,j,e);this.onApiClick.apply(this,l)},this));d.cache(this,"link",typeof c==="string"?c:c.href);if(typeof c==="string"){c=d.createA(c,e);
if(!this.preprocessLink(c))return g(c.href)}if(!f.enabled)return g(c.href);h={format:n,libid:f.library_id,out:c.href,ref:document.referrer||null,reaf:f.reaffiliate||null,title:document.title,txt:c.innerHTML};this.logTime();if(n==="go"){if(e==="_blank"&&(d.browser.ie||d.browser.opera))e=j.name=d.uniqid("win_");this.redirect(this.api("click",h,{"return":true}),j,e)}else if(j===window.self)this.api("click",h,{fn:g,timeout:f.click_timeout});else{g=d.exceptionLogger(g);setTimeout(g,f.click_timeout);j.document.open();
j.callback=g;j.document.write("<html><head><title>"+c.href+'</title><script type="text/javascript" src="'+this.api("click",h,{fn:"callback","return":true})+'"><\/script></head></html>');j.document.close()}}}(),fire:function(){var a={};return function(b,c){var e,g,h=a[b]||{fired:false,listeners:[]};if(typeof c==="function")h.fired?c({type:b}):h.listeners.push(c);else{h.fired=true;e=0;for(g=h.listeners.length;e<g;e++)typeof h.listeners[e]==="function"&&h.listeners[e]({type:b});h.listeners=[]}a[b]=h}}(),
enabled:function(){if(f.enabled&&k!==window&&window.vglnk&&(window.vglnk.key||typeof window.vglnk==="function"))f.enabled=false;return f.enabled},init:d.exceptionLogger(function(){d.exceptionLogger(d.bind(this.logException,this),true);this.initEvents();this.initNamespace();this.initOptions();this.initApi();if(this.enabled()){this.initLegacyCallbacks();this.ping()}}),initApi:function(){var a,b={};if(window.vglnk)for(a in window.vglnk)if(a.substr(-7)==="_plugin")b[a]=window.vglnk[a];m=k[i]=d.extend(function(){},
{click:d.exceptionLogger(d.bind(this.click,this)),link:d.exceptionLogger(d.bind(this.link,this)),opt:d.exceptionLogger(d.bind(this.opt,this))},m===window.vglnk?b:{})},initEvents:function(){d.on(o);d.ready(d.bind(function(){this.fire("DOMReady")},this))},initLinks:function(){var a,b,c=document.links;a=0;for(b=c.length;a<b;a++)this.link(c[a])},initNamespace:function(){if(window.vglnk&&window.vglnk.key)i="vglnk";var a=window,b=i.split("."),c;for(i=b.pop();c=b.shift();){a[c]=a[c]||{};a=a[c]}k=a;m=k[i]=
k[i]||{}},initOptions:function(){var a,b,c,e;this.initLegacyOptions();f=d.extend({api_url:null,cuid:null,dev:false,dr_key:null,enabled:!d.browser.playstation,key:null,sub_id:null,reaffiliate:false},__CF.vglnk_hash,f,m,{click_timeout:1E3,hop_timeout:2E3,debug:false,library_id:null,nofollow:{},norewrite:{},swap:{},time_click:false,time_ping:false});for(a in f)a.substr(-7)==="_plugin"&&delete f[a];if(!f.api_url){e=document.getElementsByTagName("script");a=0;for(b=e.length;a<b;a++)if(e[a].src&&(c=e[a].src.match(/^(.*)\/vglnk\.js(\?|$)\s*/))){f.api_url=
c[1];break}}},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)if(window[a]!==undefined)m[b[a]]=window[a]+(a==="vglnk_domain"?"/api":"")},initLegacyCallbacks:function(){var a,b={vl_cB:d.bind(this.onApiClick,this),vl_ping:d.bind(this.onApiPing,this),vl_disable:function(){f.enabled=false}};for(a in b)window[a]=b[a]},isRewritable:function(){var a=d.canonicalizeHostname(document.location);
return function(b){var c,e="";try{c=b.hostname;e=b.protocol;c.charAt(0)}catch(g){return false}c=d.canonicalizeHostname(b);return!(a===c||!e.match(/^https?:$/i)||f.norewrite[c]||/(^| )no(rewrite|skim)( |$)/.test(b.rel))}}(),initPlugins:function(){var a,b=1,c=d.exceptionLogger(function(){var e,g,h,j=false;for(g in a){e=window.vglnk&&window.vglnk[g+"_plugin"];h=a[g];if(e&&h){e(h,d.clone(d),m);delete a[g]}else j=true}j&&setTimeout(c,Math.min(Math.max(Math.pow(2,++b),100),5E3))});return function(e){a=
e;c()}}(),link:function(a){this.preprocessLink(a)&&d.on(a,"mouseover",d.bind(this.onMouseover,this))},log:function(a,b,c){var e="pixel.gif";if(a==="time"){e="time.gif";a={libId:f.library_id,time:c,type:b}}else if(a==="exception")a={e:b,o:c};else return;d.createEl("img").src=f.api_url+"/"+e+"?"+d.toQuery(d.extend(a,{key:f.key}))},logException:function(a){if(f.debug){var b={link:d.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};if(typeof a==="string")b.message=a;else b=d.extend(b,
a);this.log("exception",a,d.toQuery(b))}},logTime:function(){var a;return function(b){if(arguments.length===0)a=(new Date).getTime();else this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:d.exceptionLogger(function(a,b,c,e,g){var h=e||a.href,j=d.bind(function(){this.redirect(h,b,c||a.target)},this);if(typeof g==="object"&&(g.tracking||g.image)){e=d.createEl(g.tracking?"iframe":"img",{src:g.tracking||g.image},{height:0,width:0,visibility:"hidden"});document.body.appendChild(e);setTimeout(d.exceptionLogger(j),
g.timeout||f.hop_timeout)}else j()}),onApiPing:d.exceptionLogger(function(){f=d.extend(f,typeof arguments[4]==="object"?d.reformatKeys(arguments[4]):{});var a,b,c,e,g,h={2:"norewrite",3:"swap",5:"nofollow"},j=f.plugins;delete f.plugins;f.library_id=arguments[0];f.click_timeout=arguments[1];f.time_ping&&this.logTime("png");for(g in h)if(d.isArray(arguments[g])){a=arguments[g];b={};c=0;for(e=a.length;c<e;c++)if(d.isArray(a[c]))b[a[c][0]]=a[c][1];else b[a[c]]=1;f[h[g]]=d.extend(f[h[g]],b)}this.initPlugins(j);
d.on("DOMReady",d.bind(this.initLinks,this))}),onClick:d.exceptionLogger(function(a){a=a||window.event;var b=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,c=a.which&&a.which===1||a.button===0,e=d.eventLink(a);if(!(!e||b||!c||d.isDefaultPrevented(a))){this.click(e);return d.preventDefault(a)}}),onMouseover:d.exceptionLogger(function(a){if((a=d.eventLink(a||window.event))&&!d.cache(a,"evented")){d.on(a,"click",d.bind(this.onClick,this));d.cache(a,"evented",true)}}),opt:function(a){return f[a]},ping:function(){if(f.key||
f.dr_key){this.logTime();this.api("ping")}},preprocessLink:function(a){if(this.isRewritable(a)){if(f.swap[a.href])a.href=f.swap[a.href];if(f.nofollow[a.href]&&!/(^| )nofollow( |$)/.test(a.rel))a.rel=(a.rel?a.rel+" ":"")+"nofollow";return a}},redirect:function(a,b,c){if(d.browser.ie||d.browser.opera){c=d.createA(a,c);document.body.appendChild(c);c.click();c.parentNode.removeChild(c)}else setTimeout(d.exceptionLogger(function(){if(!b||b===window.self)window.location=a;else b.location.replace(a)}),0)}};
return d.extend(function(){},{click:d.exceptionLogger(d.bind(o.click,o)),init:d.exceptionLogger(d.bind(o.init,o))})}(typeof vglnk_self==="undefined"?"vglnk":vglnk_self);__CF.vglnk_load=function(){!window.skimlinks&&!window.vglnk&&__CF.vglnk.init()};
__CF.precache=function(){rl=__CF.tops;for(var i=rl.length,f,k=document,m=k.body;i--;){try{if(rl[i].toLowerCase().indexOf("http://")==-1)rl[i]=k.location.protocol+"//"+k.domain+rl[i];else if(k.location.protocol=="https:")rl[i]=rl[i].Replace("http","https")}catch(d){}if(rl[i]&&rl[i].lastIndexOf(".swf")==-1&&rl[i].lastIndexOf(".class")==-1){try{f=k.createElement("object");f.data=rl[i];f.width=f.height=0;m.appendChild(f)}catch(o){}__CF.isCookieSet(__CF.precache_cookie_name)||__CF.setCookie(__CF.precache_cookie_name,
"PRECACHE_LOADED")}else __CF.vglnk_hash.dev&&console.debug("Skipping "+rl[i])}};__CF.sendRequest=function(i,f,k,m){var d=__CF.createXMLHTTPObject();if(d){d.open(m?"POST":"GET",i,true);m&&d.setRequestHeader("Content-type","application/x-www-form-urlencoded");d.onreadystatechange=function(){if(d.readyState==4)d.status!=200&&d.status!=304?k():f(d)};d.readyState!=4&&d.send(m)}};
__CF.XMLHttpFactories=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];__CF.createXMLHTTPObject=function(){for(var i=false,f=0;f<__CF.XMLHttpFactories.length;f++){try{i=__CF.XMLHttpFactories[f]()}catch(k){continue}break}return i};__CF.load=function(){__CF.loadCFFeatures()};__CF.load();
